### ISSUE TITLE
Plans to migrate to Qgis 3

### ISSUE THREAD

**Issue by jorgealmerio** [msweier/QGIS-Profile-from-Points-Plugin#7]
Hi, do you have any plans to migrate to Qgis 3?

If you want I can help on it.

Regards,

Jorge Almerio

**Comment by msweier** [comment]
Glad you find the plugin useful Jorge. I do not have any plans on further development, so please feel free to port over.

**Comment by jorgealmerio** [comment]
I did the changes to port to Qgis 3 (Please, see my Pull request).
Please upload it to Qgis repository!

**Comment by jorgealmerio** [comment]
ProfileFromPoints is updated, it was uploaded to official repository and is already available for Qgis 3 from Plugins manager!

**Comment by cfgobel** [comment]
Hi guys, 
thanks very much for this contribution. I'm currently using 3.4 LTR and got an error installing the plugin. It is only up to version 3.0?
Best regards.

**Comment by jorgealmerio** [comment]
I have tested now with 3.4.6 LTR and got NO errors installing it.
Could you please give us more details? 
Please copy the Error log from messages (click the right bottom button to see))

**Comment by cfgobel** [comment]
Yes, sure. I just figured out that file "profileFromPoints_dialog_base.ui" is with first capital letter on the repository. Renaming it solved the problem.
But I still can reproduce the error message by reinstalling the plugin:

```
Couldn't load plugin 'ProfileFromPoints' due to an error when calling its classFactory() method 

FileNotFoundError: [Errno 2] No such file or directory: '/home/gobel/.local/share/QGIS/QGIS3/profiles/default/python/plugins/ProfileFromPoints/profileFromPoints_dialog_base.ui' 
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/qgis/utils.py", line 335, in startPlugin
    plugins[packageName] = package.classFactory(iface)
  File "/home/gobel/.local/share/QGIS/QGIS3/profiles/default/python/plugins/ProfileFromPoints/__init__.py", line 34, in classFactory
    from .profileFromPoints import ProfileFromPoints
  File "/usr/lib/python3/dist-packages/qgis/utils.py", line 672, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/home/gobel/.local/share/QGIS/QGIS3/profiles/default/python/plugins/ProfileFromPoints/profileFromPoints.py", line 31, in 
    from .profileFromPoints_dialog import ProfileFromPointsDialog
  File "/usr/lib/python3/dist-packages/qgis/utils.py", line 672, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/home/gobel/.local/share/QGIS/QGIS3/profiles/default/python/plugins/ProfileFromPoints/profileFromPoints_dialog.py", line 51, in 
    os.path.dirname(__file__), 'profileFromPoints_dialog_base.ui'))
  File "/usr/lib/python3/dist-packages/qgis/PyQt/uic/__init__.py", line 38, in __loadUiType
    return __PyQtLoadUiType(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/PyQt5/uic/__init__.py", line 198, in loadUiType
    winfo = compiler.UICompiler().compileUi(uifile, code_string, from_imports, resource_suffix, import_from)
  File "/usr/lib/python3/dist-packages/PyQt5/uic/Compiler/compiler.py", line 110, in compileUi
    w = self.parse(input_stream, resource_suffix)
  File "/usr/lib/python3/dist-packages/PyQt5/uic/uiparser.py", line 1013, in parse
    document = parse(filename)
  File "/usr/lib/python3.6/xml/etree/ElementTree.py", line 1196, in parse
    tree.parse(source, parser)
  File "/usr/lib/python3.6/xml/etree/ElementTree.py", line 586, in parse
    source = open(source, "rb")
FileNotFoundError: [Errno 2] No such file or directory: '/home/gobel/.local/share/QGIS/QGIS3/profiles/default/python/plugins/ProfileFromPoints/profileFromPoints_dialog_base.ui'


Python version: 3.6.7 (default, Oct 22 2018, 11:32:17) [GCC 8.2.0] 
QGIS version: 3.4.6-Madeira Madeira, 70d5e7e 

Python Path:
/usr/share/qgis/python
/home/gobel/.local/share/QGIS/QGIS3/profiles/default/python
/home/gobel/.local/share/QGIS/QGIS3/profiles/default/python/plugins
/usr/share/qgis/python/plugins
/usr/lib/python36.zip
/usr/lib/python3.6
/usr/lib/python3.6/lib-dynload
/usr/local/lib/python3.6/dist-packages
/usr/lib/python3/dist-packages
/home/gobel/.local/share/QGIS/QGIS3/profiles/default/python
/home/gobel/.local/share/QGIS/QGIS3/profiles/default/python/plugins/DigitizingTools/tools
/home/gobel/.local/share/QGIS/QGIS3/profiles/default/python/plugins/DigitizingTools
```

**Comment by jorgealmerio** [comment]
On windows there was no error on installing. I think because it's not a case-sensitive file system.
Anyway I fixed the first capital letter and uploaded as version 3.1.
Let me know if it's solved.

**Comment by cfgobel** [comment]
Yes, now is working without error.
Thanks
